version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: pondtech_monitoring
        container_name: pondtech_monitoring
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - laravel
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    npm:
        image: node:14
        container_name: pondtech_monitoring_npm
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: ["npm", "run", "dev"]
        networks:
            - laravel

networks:
    laravel:
