version: "3"

services:
    # Service untuk PHP-FPM (Laravel)
    php:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    # Service untuk server web (misalnya Nginx)
    # Anda bisa menggantinya dengan server web lain seperti Apache
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - app-network

    # Service untuk Node.js
    node:
        image: node:20
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
